name: "Checkin"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "npm install"
        run: npm install

      - name: "commit lint"
        uses: wagoid/commitlint-github-action@v1.2.2

      - name: "ESLint"
        run: npx @neovici/github-actions-eslint-annotator

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build"
        run: npm run build

      - name: "Upload"
        uses: actions/upload-artifact@master
        with:
          name: gdata-provider.xpi
          path: dist/gdata-provider.xpi

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Download Build Artifact"
        uses: actions/download-artifact@master
        with:
          name: gdata-provider.xpi
          path: dist

      - name: "Run Tests"
        uses: kewisch/action-thunderbird-tests@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          channel: nightly
          xpcshell: test/xpcshell/xpcshell.ini
